/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ScrollbarLazyImport = createFileRoute('/scrollbar')()
const JsonGeneratorLazyImport = createFileRoute('/json-generator')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ScrollbarLazyRoute = ScrollbarLazyImport.update({
  path: '/scrollbar',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/scrollbar.lazy').then((d) => d.Route))

const JsonGeneratorLazyRoute = JsonGeneratorLazyImport.update({
  path: '/json-generator',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/json-generator.lazy').then((d) => d.Route),
)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/json-generator': {
      preLoaderRoute: typeof JsonGeneratorLazyImport
      parentRoute: typeof rootRoute
    }
    '/scrollbar': {
      preLoaderRoute: typeof ScrollbarLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  JsonGeneratorLazyRoute,
  ScrollbarLazyRoute,
])

/* prettier-ignore-end */
